//
//  CleanModels.swift
//  CleanTest
//
//  Created by Sander Korebrits on 03/06/2019.
//  Copyright (c) 2019 Sander Korebrits. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Clean {
  // MARK: Use cases
    enum ListItem {
        
        struct Request {
        }
        
        struct Response {
            let title: String?
        }
        
        struct ViewModel {
            let label: String?
        }
  }
}
