//
//  CleanInteractor.swift
//  CleanTest
//
//  Created by Sander Korebrits on 03/06/2019.
//  Copyright (c) 2019 Sander Korebrits. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanBusinessLogic {
    func listItem(request: Clean.ListItem.Request)
}

protocol CleanDataStore {
  //var name: String { get set }
}

class CleanInteractor: CleanBusinessLogic, CleanDataStore {
    var presenter: CleanPresentationLogic?
    var worker: CleanWorker?
    //var name: String = ""

    // MARK: Do something
    func listItem(request: Clean.ListItem.Request) {
        worker = CleanWorker()
        let title = worker?.listTitle()

        let response = Clean.ListItem.Response(title: title)
        presenter?.presentListItem(response: response)
    }
}
