//
//  CleanPresenter.swift
//  CleanTest
//
//  Created by Sander Korebrits on 03/06/2019.
//  Copyright (c) 2019 Sander Korebrits. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanPresentationLogic {
    func presentListItem(response: Clean.ListItem.Response)
}

class CleanPresenter: CleanPresentationLogic {
  
    weak var viewController: CleanDisplayLogic?

    // MARK: Do something
    func presentListItem(response: Clean.ListItem.Response) {
        let viewModel = Clean.ListItem.ViewModel(label: "ViewController: \(response.title ?? "")")
        viewController?.display(viewModel: viewModel)
    }
}
