//
//  CleanViewControllerWorkerTests.swift
//  CleanTest
//
//  Created by Sander Korebrits on 03/06/2019.
//  Copyright (c) 2019 Sander Korebrits. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanInjectable
import XCTest

class CleanViewControllerWorkerTests: XCTestCase{
  
    // MARK: Subject under test
    var sut: CleanWorker!
  
    // MARK: Test lifecycle
    override func setUp(){
        super.setUp()
        setupCleanViewControllerWorker()
    }

    override func tearDown(){
        super.tearDown()
    }

    // MARK: Test setup

    func setupCleanViewControllerWorker(){
        sut = CleanWorker()
    }

    // MARK: Test doubles

    // MARK: Tests
    func testSomething(){
        // Given
        
        // When
        
        // Then
        XCTAssertEqual(sut.listTitle(), "Clean")
    }
}
